### ISSUE TITLE
Test Suite for Python Bindings

### ISSUE THREAD

**Issue by SamFurman** [LLNL/mpibind#17]
Per our 8/13/2020 discussion we would like to test the python bindings by leveraging the work Nick has done in testing the C bindings of mpibind. To make this happen, the following needs to be done:

- Add wrapper functions around some hwloc functions that return parameters for tests
- Mimic Nick's test generation on python side using wrapped hwloc functions
- Write a function that translates mpibind mapping on python side into expected file format
- Fix python tap runner

**Comment by eleon** [comment]
The Python test suite has been implemented and merged into master through PR #23.
