### ISSUE TITLE
add option to disable GPU binding on Flux

### ISSUE THREAD

**Issue by garlick** [LLNL/mpibind#43]
A user requested a way to tell mpibind not to bind gpus, e.g. not set ROCR_VISIBLE_DEVICES

I see there is a `gpu:0` option for slurm.  Maybe this could be added for Flux?  Or maybe there is already a way to do this and I am not seeing it.

**Comment by eleon** [comment]
This can be done via `-o mpibind=visible_devices` Here's an example. 

Nominal behavior: 
``` 
$ flux run -N1 -n4 --exclusive env | grep VISIBLE
ROCR_VISIBLE_DEVICES=2,3
ROCR_VISIBLE_DEVICES=6,7
ROCR_VISIBLE_DEVICES=4,5
ROCR_VISIBLE_DEVICES=0,1
```
Disable GPU affinity
```
$ flux run -N1 -n4 --exclusive -o mpibind=visible_devices env | grep VISIBLE
ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
```
