### ISSUE TITLE
add manual page for flux

### ISSUE THREAD

**Issue by garlick** [LLNL/mpibind#44]
Problem: A user noted that mpibind options are not documented outside of tutorial information.

It may be helpful for mpibind to provide a `flux-mpibind(1)` man page that contains
* SYNOPSIS showing various `flux run -o mpibind=...` options
* DESCRIPTION describing  mpibind's role
* SHELL OPTIONS section describing options in detail, following a similar pattern to [flux-shell(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/stable/man1/flux-shell.html)
* SEE ALSO referring to flux-shell(1), flux-run(1).

**Comment by eleon** [comment]
The options of mpibind for Flux have been documented via 27d7fe5fe4d1efb610a85494d3030cc349a0b4df
